#### Introduction To Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [7]:
# Create Tensors
scaler = tf.constant(7)
print(scaler)
print(scaler.ndim)
print(scaler.shape)
print(scaler.dtype)

tf.Tensor(7, shape=(), dtype=int32)
0
()
<dtype: 'int32'>


In [8]:
# Create Tensors
scaler = tf.constant([1,2,3],dtype=tf.float16)
print(scaler)
print(scaler.ndim)
print(scaler.shape)
print(scaler.dtype)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float16)
1
(3,)
<dtype: 'float16'>


In [15]:
# Create Tensor with tf.Variable 
changeable_tensor = tf.Variable([10,7])
print(changeable_tensor)
# print(changeable_tensor.ndim)  # ERROR
print(changeable_tensor.shape)
print(changeable_tensor.dtype)

changeable_tensor[0].assign(20)
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
(2,)
<dtype: 'int32'>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20,  7], dtype=int32)>


In [25]:
# Create Random Tensor
gen = tf.random.Generator.from_seed(42)
random_1 = gen.uniform(shape=(1,2))
print(random_1)

random_2 = gen.normal(shape=(1,2))
print(random_2)

tf.Tensor([[0.7493447  0.73561966]], shape=(1, 2), dtype=float32)
tf.Tensor([[ 0.9029392  -0.12441138]], shape=(1, 2), dtype=float32)


In [41]:
# Shuffle Tensor
scaler = tf.constant([1,2,3,4,5,6],dtype=tf.float16)
tf.random.set_seed(42)
tf.random.shuffle(scaler,seed=2)

<tf.Tensor: shape=(6,), dtype=float16, numpy=array([1., 6., 5., 3., 4., 2.], dtype=float16)>

In [52]:
# Other Ways to Make Tensor
print(tf.ones([2,2]))

print("---"*10)

print(tf.zeros([2,2]))

print("---"*10)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
------------------------------
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
------------------------------


#### Tensor Information
When dealing with tensors you must be familier with following attributes
- Shape
- Size
- Rank
- Axis or dimension
- Size
- Indexing

In [61]:
scaler = tf.constant([[1,2,3],[4,5,6]],dtype=tf.float16)

print(scaler.shape)
print(tf.size(scaler))
print(scaler.ndim)
print(scaler._rank())
print(scaler.dtype)
print(scaler[:,:2])

(2, 3)
tf.Tensor(6, shape=(), dtype=int32)
2
2
<dtype: 'float16'>
tf.Tensor(
[[1. 2.]
 [4. 5.]], shape=(2, 2), dtype=float16)


In [69]:
scaler[...,tf.newaxis]

<tf.Tensor: shape=(2, 3, 1), dtype=float16, numpy=
array([[[1.],
        [2.],
        [3.]],

       [[4.],
        [5.],
        [6.]]], dtype=float16)>

In [80]:
tf.expand_dims(scaler,axis=2)

<tf.Tensor: shape=(2, 3, 1), dtype=float16, numpy=
array([[[1.],
        [2.],
        [3.]],

       [[4.],
        [5.],
        [6.]]], dtype=float16)>

In [82]:
# Some Operations
print(scaler)

print("---"*10)

print(tf.multiply(scaler,10))

print("---"*10)

print(tf.add(scaler,10))

print("---"*10)

print(tf.subtract(scaler,10))

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float16)
------------------------------
tf.Tensor(
[[10. 20. 30.]
 [40. 50. 60.]], shape=(2, 3), dtype=float16)
------------------------------
tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float16)
------------------------------
tf.Tensor(
[[-9. -8. -7.]
 [-6. -5. -4.]], shape=(2, 3), dtype=float16)


#### Tensor Multiplication

Tensor Multiplication is also referred as dot-product.

- tf.matmul()
- tf.tensordot()

In [86]:
mat1 = tf.constant([[2,5,3],[2,8,3]])
mat2 = tf.constant([[2,3,3],[2,1,5],[2,3,4]])

tf.matmul(mat1,mat2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[20, 20, 43],
       [26, 23, 58]], dtype=int32)>

In [94]:
tf.tensordot(mat1,mat2,axes=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[20, 20, 43],
       [26, 23, 58]], dtype=int32)>

In [88]:
tf.transpose(mat1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 2],
       [5, 8],
       [3, 3]], dtype=int32)>

In [92]:
tf.reshape(mat1,(3,-1))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [3, 2],
       [8, 3]], dtype=int32)>

#### Change Data Type

In [95]:
mat1 = tf.constant([[2,5,3],[2,8,3]],dtype='int32')

tf.cast(mat1,dtype='float32')

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 5., 3.],
       [2., 8., 3.]], dtype=float32)>

#### Tensor Aggregation